### ISSUE TITLE
TypeError: t.indexOf is not a function when using node.js

### ISSUE THREAD

**Issue by veprogames** [antimatter-dimensions/notations#344]
Steps to reproduce:

* `npm init`
* `npm i @antimatter-dimensions/notations break_infinity.js`

installed Packages:
* "@antimatter-dimensions/notations": "^3.0.3",
* "break_infinity.js": "^2.0.0"

Test Script:
```js
const Decimal = require("break_infinity.js");
const ADNotations = require("@antimatter-dimensions/notations")

const notation = new ADNotations.StandardNotation();

console.log(notation.formatDecimal(new Decimal(1)));
```

Trace (.\ is project root):
```
TypeError: t.indexOf is not a function
    at t.fromString (.\node_modules\break_infinity.js\dist\break_infinity.common.js:1:6465)
    at new t (.\node_modules\break_infinity.js\dist\break_infinity.common.js:1:743)
    at i (.\node_modules\break_infinity.js\dist\break_infinity.common.js:1:243)
    at t.div (.\node_modules\break_infinity.js\dist\break_infinity.common.js:1:10392)
    at .\node_modules\@antimatter-dimensions\notations\dist\ad-notations.umd.js:106:24
    at StandardNotation.formatDecimal (.\node_modules\@antimatter-dimensions\notations\dist\ad-notations.umd.js:413:110)
    at Object.<anonymous> (.\index.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by veprogames** [comment]
Updated to 3.0.4, it works now 👍
